[project]
name = "nexus-agent"
version = "0.1.0"
description = "AI coding agent for the terminal"
requires-python = ">=3.11"

dependencies = [
    "pydantic",
    "rich",
    "openai",
    "tomli",
    "platformdirs",
    "click",
    "playwright",
    "ddgs",
    "httpx",
    "tweepy",
    "requests",
    "langchain_core",
    "langchain_chroma",
    "langchain",
    "pdfminer.six",
    "unstructured[pdf]",
    "unstructured",
    "langchain_openai",
    "langchain_community",
    "sentence-transformers"'
]

[project.scripts]
nexus = "nexus_agent.main:main"